import { jsPDF } from 'jspdf';
import type { PredictionResultData } from '@/components/PredictionResult';

function sanitizePdfText(value: unknown, maxLength = 200): string {
  return String(value ?? '')
    .normalize('NFKC')
    .replace(/[\u0000-\u001F\u007F]/g, ' ')
    .replace(/[<>`]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, maxLength);
}

export function generatePdfReport(result: PredictionResultData): void {
  const doc = new jsPDF();
  const isFraud = result.prediction === 'Fraud';
  const riskLevel = result.probability < 40 ? 'Low Risk' : result.probability < 70 ? 'Medium Risk' : 'High Risk';

  const primary = [67, 97, 238];
  const danger = [220, 53, 69];
  const success = [16, 185, 129];
  const textColor = isFraud ? danger : success;

  doc.setFillColor(primary[0], primary[1], primary[2]);
  doc.rect(0, 0, 210, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Anqor', 15, 15);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Fraud Detection Analysis Report', 15, 23);

  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 15, 30);

  let y = 50;
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(result.prediction === 'Fraud' ? 'FRAUDULENT CLAIM DETECTED' : 'LEGITIMATE CLAIM', 15, y);

  y += 15;
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Risk Score: ${result.probability}%`, 15, y);

  y += 8;
  doc.text(`Risk Level: ${riskLevel}`, 15, y);

  y += 8;
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(15, y, 120, 6, 3, 3, 'F');

  const barColor = result.probability < 40 ? success : result.probability < 70 ? [234, 179, 8] : danger;
  doc.setFillColor(barColor[0], barColor[1], barColor[2]);
  doc.roundedRect(15, y, (result.probability / 100) * 120, 6, 3, 3, 'F');

  y += 16;
  doc.setDrawColor(200, 200, 200);
  doc.line(15, y, 195, y);

  y += 12;
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Fraud Indicators', 15, y);

  y += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  for (const indicator of result.indicators.map((value) => sanitizePdfText(value, 180))) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    doc.setFillColor(textColor[0], textColor[1], textColor[2]);
    doc.circle(19, y - 1.5, 1.5, 'F');

    doc.setTextColor(80, 80, 80);
    doc.text(indicator, 25, y);
    y += 8;
  }

  y = 280;
  doc.setDrawColor(200, 200, 200);
  doc.line(15, y - 5, 195, y - 5);
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('This report was generated by Anqor - AI-Powered Fraud Detection Platform', 15, y);

  const date = new Date().toISOString().slice(0, 10);
  const claimType = sanitizePdfText(result.claimType || 'claim', 40).replace(/[^a-zA-Z0-9_-]/g, '-');
  doc.save(`anqor-${claimType || 'claim'}-report-${date}.pdf`);
}
