"""
Anqor — PDF Report Generator
=======================================
Generates bulk PDF reports from prediction results.
Uses fpdf2 library for PDF generation.
"""


def generate_bulk_pdf_report(results: list, claim_type: str) -> bytes:
    """
    Generate a consolidated PDF report for batch prediction results.
    Returns PDF content as bytes.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        # Fallback: generate a minimal PDF manually
        return _generate_minimal_pdf(results, claim_type)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Cover Page ──
    pdf.add_page()
    pdf.set_fill_color(67, 97, 238)
    pdf.rect(0, 0, 210, 40, 'F')

    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 22)
    pdf.set_y(10)
    pdf.cell(0, 10, 'Anqor', ln=True, align='L')
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(0, 7, f'Bulk Fraud Detection Report — {claim_type.title()} Insurance', ln=True, align='L')

    from datetime import datetime
    pdf.set_font('Helvetica', '', 9)
    pdf.cell(0, 7, f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', ln=True, align='L')

    # ── Summary ──
    pdf.set_y(55)
    pdf.set_text_color(40, 40, 40)
    pdf.set_font('Helvetica', 'B', 16)
    pdf.cell(0, 10, 'Executive Summary', ln=True)

    total = len(results)
    fraud_count = sum(1 for r in results if r.get('prediction') in ('Y', 'Fraud', 1, '1'))
    legit_count = total - fraud_count
    avg_prob = sum(float(r.get('probability', 0)) for r in results) / max(total, 1)
    high_risk = sum(1 for r in results if float(r.get('probability', 0)) >= 0.7)

    pdf.set_font('Helvetica', '', 11)
    summary_items = [
        f'Total Claims Analyzed: {total}',
        f'Fraudulent Claims Detected: {fraud_count} ({fraud_count / max(total, 1) * 100:.1f}%)',
        f'Legitimate Claims: {legit_count}',
        f'Average Fraud Probability: {avg_prob:.2%}',
        f'High-Risk Claims (>70%): {high_risk}',
    ]
    for item in summary_items:
        pdf.cell(0, 8, f'  • {item}', ln=True)

    # ── Results Table ──
    pdf.ln(10)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 10, 'Detailed Results', ln=True)

    # Table header
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_fill_color(240, 240, 240)
    col_widths = [15, 25, 30, 25, 95]
    headers = ['#', 'Prediction', 'Probability', 'Risk', 'Top Indicators']

    for i, (header, w) in enumerate(zip(headers, col_widths)):
        pdf.cell(w, 8, header, border=1, fill=True)
    pdf.ln()

    # Table rows
    pdf.set_font('Helvetica', '', 8)
    for i, r in enumerate(results):
        if pdf.get_y() > 265:
            pdf.add_page()
            # Repeat header
            pdf.set_font('Helvetica', 'B', 9)
            pdf.set_fill_color(240, 240, 240)
            for header, w in zip(headers, col_widths):
                pdf.cell(w, 8, header, border=1, fill=True)
            pdf.ln()
            pdf.set_font('Helvetica', '', 8)

        pred = r.get('prediction', 'N/A')
        prob = float(r.get('probability', 0))
        risk = r.get('risk_level', 'unknown')
        indicators = r.get('indicators', [])
        top_ind = '; '.join(indicators[:2]) if indicators else 'None'

        # Color code prediction
        if pred in ('Y', 'Fraud', 1, '1'):
            pdf.set_text_color(220, 53, 69)
        else:
            pdf.set_text_color(16, 185, 129)

        pdf.cell(col_widths[0], 7, str(i + 1), border=1)
        pdf.cell(col_widths[1], 7, str(pred), border=1)
        pdf.set_text_color(40, 40, 40)
        pdf.cell(col_widths[2], 7, f'{prob:.2%}', border=1)
        pdf.cell(col_widths[3], 7, risk, border=1)
        pdf.cell(col_widths[4], 7, top_ind[:90], border=1)
        pdf.ln()

    # ── Footer ──
    pdf.set_y(-20)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, 'Generated by Anqor — AI-Powered Insurance Fraud Detection', align='C')

    return pdf.output()


def _generate_minimal_pdf(results: list, claim_type: str) -> bytes:
    """
    Minimal PDF generation without fpdf2 dependency.
    Creates a very basic PDF with text content.
    """
    from datetime import datetime

    total = len(results)
    fraud_count = sum(1 for r in results if r.get('prediction') in ('Y', 'Fraud', 1, '1'))

    text_lines = [
        'Anqor - Bulk Fraud Detection Report',
        f'Claim Type: {claim_type.title()} Insurance',
        f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
        '',
        f'Total Claims: {total}',
        f'Fraud Detected: {fraud_count}',
        f'Legitimate: {total - fraud_count}',
        '',
        'Results:',
    ]

    for i, r in enumerate(results[:50]):  # Cap at 50 for minimal PDF
        pred = r.get('prediction', 'N/A')
        prob = float(r.get('probability', 0))
        risk = r.get('risk_level', 'unknown')
        text_lines.append(f'  #{i + 1}: {pred} | Prob: {prob:.2%} | Risk: {risk}')

    content = '\n'.join(text_lines)

    # Build minimal valid PDF
    pdf_content = b'%PDF-1.4\n'
    pdf_content += b'1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'
    pdf_content += b'2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n'
    pdf_content += b'3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n'

    stream_content = f'BT\n/F1 10 Tf\n'
    y = 750
    for line in content.split('\n'):
        safe_line = line.replace('\\', '\\\\').replace('(', '\\(').replace(')', '\\)')
        stream_content += f'1 0 0 1 50 {y} Tm\n({safe_line}) Tj\n'
        y -= 14
        if y < 50:
            break
    stream_content += 'ET\n'

    stream_bytes = stream_content.encode('latin-1', errors='replace')
    pdf_content += f'4 0 obj\n<< /Length {len(stream_bytes)} >>\nstream\n'.encode()
    pdf_content += stream_bytes
    pdf_content += b'\nendstream\nendobj\n'
    pdf_content += b'5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>\nendobj\n'

    xref_pos = len(pdf_content)
    pdf_content += b'xref\n0 6\n'
    pdf_content += b'0000000000 65535 f \n'
    pdf_content += b'0000000009 00000 n \n'
    pdf_content += b'0000000058 00000 n \n'
    pdf_content += b'0000000115 00000 n \n'
    pdf_content += b'0000000266 00000 n \n'
    pdf_content += f'0000000{300 + len(stream_bytes):03d} 00000 n \n'.encode()
    pdf_content += f'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n'.encode()

    return pdf_content
